# Generated by Django 3.2.12 on 2024-03-28 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-date_ajout',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='carouselHero')),
                ('date_ajout', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='ShopApp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='carouselHero')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.categorie')),
            ],
        ),
    ]
