# Generated by Django 3.2.12 on 2024-04-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_alter_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=50)),
                ('telephone_client', models.CharField(max_length=50)),
                ('email_client', models.CharField(max_length=50)),
                ('adresse_client', models.CharField(max_length=50)),
                ('ville_client', models.CharField(max_length=50)),
                ('pays_client', models.CharField(max_length=50)),
                ('rue', models.CharField(blank=True, max_length=50)),
                ('numero_maison', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('montant', models.FloatField()),
                ('date_commande', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='produit_commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.commande')),
            ],
        ),
    ]
